server:
  port: 5000
spring:
  application:
    name: kamalov_sat
  datasource:
    url: jdbc:postgresql://database-1.clagyigiaa43.eu-central-1.rds.amazonaws.com:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: begaliev
    password: begaliev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: db/changelog/changelog-master.yml
    enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: false
logging:
  level:
    kg.kamalov_sat: INFO
