server:
  port: 8080
spring:
  application:
    name: kamalov_sat
  datasource:
    url: jdbc:postgresql://localhost:5432/kamalov_sat
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: db/changelog/changelog-master.yml
    enabled: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    kg.kamalov_sat: INFO